let lastCnt=null;
const periodOf=h=>h>=5&&h<12?'morning':h>=12&&h<17?'afternoon':h>=17&&h<21?'evening':'night';
const SUPPORT={morning:'A new day, a clear plan. Here is what needs your attention.',afternoon:"Keep the momentum going. You still have time to move today's priorities forward.",evening:"Review what you accomplished today and prepare tomorrow's priorities.",night:'Your work for today is done. Rest well and return tomorrow with a clear plan.'};
function clockParts(d=new Date()){let h=d.getHours();const ap=h>=12?'PM':'AM',p=n=>String(n).padStart(2,'0');h=h%12||12;return{hm:p(h)+':'+p(d.getMinutes()),s:p(d.getSeconds()),ap,date:d.toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long',year:'numeric'}),per:periodOf(d.getHours())}}
const tick=setInterval(()=>{const e=document.getElementById('clk');if(!e||!e.querySelector)return;const c=clockParts();e.querySelector('.hm').textContent=c.hm;e.querySelector('.sec').textContent=':'+c.s;e.querySelector('.ap').textContent=c.ap;document.getElementById('cdate').textContent=c.date;document.getElementById('greet').textContent='Good '+c.per+nm()+'.';document.getElementById('sup').textContent=SUPPORT[c.per]},1000);tick.unref&&tick.unref();
let pstage='',trng=30;const STAGES=['Researching','Preparing','Submitted','Interview','Decision'];
function trendHtml(){if(S.apps.length<2)return empty('Not enough data yet.<br>As you add and progress applications, your activity will appear here.');
const n={7:7,30:10,90:9,365:12}[trng],step=trng/n,bins=Array(n).fill(0);S.apps.forEach(a=>{const ago=-days(a.created||a.updated);if(ago>=0&&ago<trng)bins[n-1-Math.floor(ago/step)]++});
const mx=Math.max(1,...bins),pts=bins.map((c,i)=>[i/(n-1)*600,130-c/mx*110]),line=pts.map(p=>p.join(',')).join(' ');
return `<svg viewBox="0 0 600 140" preserveAspectRatio="none" style="width:100%;height:140px" role="img" aria-label="Applications added over time"><polygon points="0,130 ${line} 600,130" fill="var(--acs)"/><polyline points="${line}" fill="none" stroke="var(--ac)" stroke-width="2" vector-effect="non-scaling-stroke"/></svg><small>${bins.reduce((x,y)=>x+y,0)} applications added in this period</small>`}
function outlookHtml(){const it=S.opps.filter(o=>o.status!=='Archived'&&days(o.deadline)>=0&&days(o.deadline)<=30).sort((a,b)=>a.deadline<b.deadline?-1:1);if(!it.length)return empty('No deadlines in the next 30 days.');
return `<div class="tl"><div class="axis"></div>${[0,7,14,30].map(d=>`<span class="tk" style="left:${d/30*100}%">${d?d+'d':'Today'}</span>`).join('')}${it.slice(0,8).map((o,i)=>{const p=days(o.deadline)/30*100;return `<span class="dot lnk" data-act="openopp" data-id="${o.id}" style="${p>60?'right:'+(100-p):'left:'+p}%;top:${26+(i%3)*22}px">● ${esc(o.title.slice(0,26))}</span>`}).join('')}</div>`}
views.overview=()=>{const A=getNextBestActions(),c=clockParts(),pri=A.filter(a=>['critical','high'].includes(a.priority)&&!S.doneActions.includes(a.id)).length;
const apps=S.apps,tot=apps.length,cnt=s=>apps.filter(a=>a.status===s).length,act=apps.filter(a=>!['Accepted','Rejected'].includes(a.status)),dls=S.opps.filter(o=>o.status!=='Archived'&&days(o.deadline)>=0);
const soon=act.filter(a=>days(opp(a.oid).deadline)<=7&&days(opp(a.oid).deadline)>=0).length,wait=apps.filter(a=>['Submitted','Interview','Decision'].includes(a.status)).length+S.opps.filter(o=>o.contact&&o.contact.status==='Email sent').length;
const K=[[S.opps.length,'Opportunities'],[act.length,'Active applications'],[A.filter(a=>a.id.startsWith('fu')).length,'Follow-ups'],[dls.length,'Upcoming deadlines']];
const prevC=lastCnt;lastCnt=Object.fromEntries(STAGES.map(s=>[s,cnt(s)]));
return `<div class="hero"><div class="eyebrow" id="greet">Good ${c.per}${nm()}.</div><div id="clk"><span class="hm">${c.hm}</span><span class="ap">${c.ap}</span><span class="sec">:${c.s}</span></div><div id="cdate">${c.date}</div><p id="sup" class="sub" style="margin:10px 0">${SUPPORT[c.per]}</p>
<p>${pri?`You have ${pri} ${pri===1?'priority':'priorities'} requiring attention today.`:"Nothing urgent today."}</p><div class="bar"><button class="btn p" data-act="gomission">View today's mission</button></div></div>
${S.demo?'<div class="bar"><span class="demo">Demo Mode</span><small>Sample records are shown.</small><button class="btn" data-act="cleardemo">Clear demo data</button></div>':''}
${momentHtml()}<div id="mission">${missionHtml(6)}</div><div class="kpis">${K.map(k=>`<div><b>${k[0]}</b><span>${k[1]}</span></div>`).join('')}</div>
<div class="panel"><h3>Application pipeline</h3>${tot?`<div class="pipe">${STAGES.map(s=>`<button class="stage ${pstage===s?'sel':''}" data-act="pstage" data-k="${s}"><small>${s.toUpperCase()}</small><b data-count="d:${s}">${cnt(s)}</b>${prevC&&prevC[s]!==undefined&&prevC[s]!==cnt(s)?`<small class="chg">${prevC[s]} → ${cnt(s)}</small>`:''}<i class="pbar" data-grow style="width:${cnt(s)/tot*100}%"></i><small>${Math.round(cnt(s)/tot*100)}% of pipeline</small></button>`).join('')}</div>
<div class="tiles"><div><b>${tot}</b><small>Total tracked</small></div><div><b>${act.length}</b><small>Currently active</small></div><div><b>${cnt('Accepted')}</b><small>Accepted</small></div><div><b>${cnt('Rejected')}</b><small>Rejected</small></div></div>
${pstage?`<h3 style="margin-top:14px">${pstage} · ${cnt(pstage)} applications</h3>${apps.filter(a=>a.status===pstage).map(a=>`<div class="row"><span class="lnk" data-act="openopp" data-id="${a.oid}">${esc(opp(a.oid).title)}</span><small>${esc(opp(a.oid).inst)}</small></div>`).join('')||'<small>None at this stage.</small>'}`:''}
<h3 style="margin-top:14px">Your pipeline</h3><small style="display:block">${act.length} active applications · ${A.filter(a=>a.type==='application'&&['critical','high'].includes(a.priority)).length} need attention today · ${soon} with a deadline within 7 days · ${wait} awaiting external responses</small>`:empty('Not enough data yet.<br>Start an application from one of your opportunities.')}</div>
<div class="cols"><div class="panel"><div class="row" style="border:0;padding:0"><h3 style="margin:0">Application activity</h3><span>${[7,30,90,365].map(r=>`<button class="btn ${trng===r?'p':''}" data-act="trange" data-k="${r}">${r===365?'1Y':r+'D'}</button>`).join(' ')}</span></div>${trendHtml()}</div><div class="panel"><h3>Deadline outlook</h3>${outlookHtml()}</div></div>
<div class="panel"><div class="row" style="border:0"><h3 style="margin:0">Recent opportunities</h3><button class="btn p" data-act="addopp">+ Add Opportunity</button></div>${[...S.opps].sort((a,b)=>a.added<b.added?1:-1).slice(0,3).map(oppCard).join('')||empty('Your opportunity list is empty.','<button class="btn p" data-act="addopp">+ Add Opportunity</button>')}</div>`};
Object.assign(ACTIONS,{pstage(id,t){pstage=pstage===t.dataset.k?'':t.dataset.k;render()},trange(id,t){trng=+t.dataset.k;render()},clrf(){ofk='all';ofl={};oq='';render()},
gomission:()=>document.getElementById('mission').scrollIntoView({behavior:'smooth'}),
cleardemo(){S.opps=[];S.apps=[];S.prof=[];S.demo=false;save();render();toast('Demo data cleared')}});
