S.doneActions=S.doneActions||[];if(S.doneDate!==D(0)){S.doneActions=[];S.doneDate=D(0)}
function missionHtml(n=6){const A=getNextBestActions(),dn=A.filter(a=>S.doneActions.includes(a.id)).length;
return `<div class="panel"><div class="row" style="border:0"><div><h3 style="font-size:15px;margin:0">Today's mission</h3><small>${A.length-dn} actions require your attention</small></div><div style="text-align:right"><small>${dn} / ${A.length} completed</small><div class="prog" style="width:140px"><i style="width:${A.length?dn/A.length*100:0}%"></i></div></div></div>
${A.slice(0,n).map(a=>{const d=S.doneActions.includes(a.id);return `<div class="row ${d?'done':''}" data-mi="${a.id}"><div><span class="tag ${PCLS[a.priority]}">${a.priority.toUpperCase()}</span> <b>${esc(a.title)}</b><small>${esc(a.sub)} · ${esc(a.reason)}${a.due?' · '+fmt(a.due):''}</small>${a.progress!=null?`<div class="prog" style="margin-top:4px"><i style="width:${a.progress}%"></i></div>`:''}</div><span style="white-space:nowrap"><button class="btn p" data-act="mission" data-id="${a.id}">${esc(a.cta)}</button> <button class="btn" data-act="mdone" data-id="${a.id}">${d?'Undo':'Done'}</button></span></div>`}).join('')||empty(`You're all caught up${nm()}.`)}</div>`}
views.overview=()=>{const A=getNextBestActions(),hr=new Date().getHours(),g=hr<12?'Good morning':hr<18?'Good afternoon':'Good evening';
const act=S.apps.filter(a=>!['Accepted','Rejected'].includes(a.status)),dls=S.opps.filter(o=>o.status!=='Archived'&&days(o.deadline)>=0).sort((a,b)=>a.deadline<b.deadline?-1:1),att=A.filter(a=>a.type==='application'&&['critical','high'].includes(a.priority)).length;
const K=[[S.opps.length,'Opportunities'],[act.length,'Active applications'],[A.filter(a=>a.type==='outreach'&&a.priority!=='medium').length,'Follow-ups'],[dls.length,'Upcoming deadlines']];
return `<h2>${g}${nm()}.</h2><p class="sub">Here's what's happening with your graduate applications.${att?` ${att} ${att===1?'application needs':'applications need'} attention.`:''}</p>
<div class="kpis">${K.map(k=>`<div><b>${k[0]}</b><span>${k[1]}</span></div>`).join('')}</div>${missionHtml(6)}
<div class="panel"><div class="row" style="border:0"><h3 style="margin:0">Recent opportunities</h3><button class="btn p" data-act="addopp">+ Add Opportunity</button></div>${[...S.opps].sort((a,b)=>a.added<b.added?1:-1).slice(0,3).map(oppCard).join('')||empty('Nothing here yet.','<button class="btn p" data-act="addopp">Add your first opportunity</button>')}</div>
<div class="cols"><div class="panel"><h3>Application pipeline</h3>${STAT.map(s=>`<div class="row"><span>${s}</span><b>${S.apps.filter(a=>a.status===s).length}</b></div>`).join('')}</div>
<div class="panel"><h3>Upcoming deadlines</h3>${dls.slice(0,5).map(o=>{const a=S.apps.find(x=>x.oid===o.id);return `<div class="row"><div><span class="lnk" data-act="openopp" data-id="${o.id}">${esc(o.title)}</span><small>${fmt(o.deadline)}</small>${a&&!FINISHED.includes(a.status)?`<small>Risk: ${deadlineRisk(a).level}</small>`:''}</div>${dtag(o.deadline)}</div>`}).join('')||empty('No open deadlines.')}</div></div>`};
