const COUNTRIES=['Canada','United States','United Kingdom','Germany','Netherlands','Australia','Ireland','Sweden','Switzerland','Other'],DEGREES=["Master's",'PhD','MPhil','Postgraduate Diploma','Fellowship','Other'],FUNDING=['Fully Funded','Partially Funded','Scholarship','Studentship','Assistantship','Fellowship','Tuition Waiver','Grant','Other'],SOURCES=['University Website','FindAPhD','FindAMasters','LinkedIn','Scholarship Website','Professor','Government Portal','Other'],OSTAT=['Interested','Researching','Preparing','Applied','Not Pursuing','Archived'],PRIO=['High','Medium','Low'];
let ofk='all',ofl={};
const OF={all:()=>1,active:o=>['Interested','Researching','Preparing'].includes(o.status),saved:o=>o.saved,closing:o=>days(o.deadline)>=0&&days(o.deadline)<=14&&!['Applied','Archived','Not Pursuing'].includes(o.status),applied:o=>o.status==='Applied',archived:o=>o.status==='Archived'};
const sel=(n,arr,v,x='')=>`<select ${x} name="${n}">${arr.map(a=>`<option ${a===v?'selected':''}>${a}</option>`).join('')}</select>`;
function oppCard(o){return `<div class="panel oppcard"><b class="lnk" data-act="openopp" data-id="${o.id}">${esc(o.title)}</b><br><small>${esc(o.inst)}${o.country?' · '+esc(o.country):''}</small>
<p style="margin:8px 0"><small>${[o.funding,o.degree,o.fields.slice(0,2).join(', ')].filter(Boolean).map(esc).join(' · ')}</small></p>${o.deadline?`<small>Deadline: ${fmt(o.deadline)}</small> ${dtag(o.deadline)}<br>`:''}${o.source?`<small>Source: ${esc(o.source)}</small>`:''}
<div class="bar"><select data-act="ost" data-id="${o.id}" aria-label="Status">${OSTAT.map(s=>`<option ${s===o.status?'selected':''}>${s}</option>`).join('')}</select><button class="btn p" data-act="openopp" data-id="${o.id}">Open</button><button class="btn" data-act="start" data-id="${o.id}">Start Application</button><button class="btn" data-act="save" data-id="${o.id}">${o.saved?'Saved ✓':'Save'}</button></div></div>`}
let oq='';
views.opps=()=>{const uniq=f=>[...new Set(S.opps.flatMap(f))].filter(Boolean).sort(),dd=(k,l,arr)=>`<select data-act="ofil" data-k="${k}" aria-label="${l}"><option value="">${l}</option>${arr.map(x=>`<option ${ofl[k]===x?'selected':''}>${esc(x)}</option>`).join('')}</select>`;
const l=S.opps.filter(o=>(ofk==='all'||o.status===ofk)&&(!oq||(o.title+o.inst+o.country+o.fields.join()).toLowerCase().includes(oq.toLowerCase()))&&(!ofl.c||o.country===ofl.c)&&(!ofl.d||o.degree===ofl.d)&&(!ofl.f||o.funding===ofl.f)).sort((a,b)=>a.added<b.added?1:-1);
const act=S.apps.filter(a=>!['Accepted','Rejected'].includes(a.status)).length,filtered=ofk!=='all'||oq||Object.values(ofl).some(Boolean);
if(!S.opps.length)return `<h2>My Opportunities</h2>${empty('Your opportunity list is empty.<br>Add scholarships, funded positions and graduate opportunities you find elsewhere.','<button class="btn p" data-act="addopp">+ Add Opportunity</button>')}`;
return `<div class="bar" style="justify-content:space-between"><div><h2>My Opportunities</h2><p class="sub" style="margin:0">Scholarships, funded positions and other opportunities you have found and want to track.</p></div><button class="btn p" data-act="addopp">+ Add Opportunity</button></div>
<div class="bar"><small style="color:var(--tx2)">${S.opps.length} opportunities · ${act} active applications</small></div>
<div class="bar">${['all','Interested','Researching','Preparing','Applied','Archived'].map(k=>`<button class="btn ${ofk===k?'p':''}" data-act="ofilt" data-k="${k}">${k==='all'?'All':k}</button>`).join('')}<input id="oq" type="search" placeholder="Search my opportunities…" value="${esc(oq)}" aria-label="Search my opportunities">${dd('c','Country',uniq(o=>[o.country]))}${dd('d','Degree',uniq(o=>[o.degree]))}${dd('f','Funding type',uniq(o=>[o.funding]))}${filtered?'<button class="btn" data-act="clrf">Clear filters</button>':''}</div>
${l.map(oppCard).join('')||empty('No opportunities match these filters.','<button class="btn" data-act="clrf">Clear filters</button>')}`};
views.opp=()=>{const o=S.opps.find(x=>x.id===vid);if(!o)return empty('Opportunity not found.','<button class="btn" data-act="go" data-v="opps">Back</button>');
const a=S.apps.find(x=>x.oid===o.id),ps=S.prof.filter(p=>p.oid===o.id),sh=sharedAreas(S.profile.areas,o.fields),dn=o.reqs.filter(r=>r.done).length,row=(l,v)=>v?`<div class="row"><span>${l}</span><span>${v}</span></div>`:'';
return `<p><button class="btn" data-act="go" data-v="opps">← Opportunities</button></p><div class="bar" style="justify-content:space-between"><div><h2>${esc(o.title)}</h2><p class="sub" style="margin:0">${esc(o.inst)}${o.city?', '+esc(o.city):''}${o.country?' · '+esc(o.country):''}</p></div><div class="bar"><button class="btn" data-act="editopp" data-id="${o.id}">Edit</button><button class="btn" data-act="askdel" data-id="${o.id}">Delete</button></div></div>
<div class="cols"><div><div class="panel"><h3>Overview</h3>${row('Degree',esc(o.degree))}${row('Deadline',o.deadline?fmt(o.deadline)+' '+dtag(o.deadline):'')}${row('Status',esc(o.status))}${row('Priority',esc(o.priority))}${row('Source',esc(o.source))}${row('Eligibility',esc(o.elig))}</div>
<div class="panel"><h3>Funding</h3>${row('Type',esc(o.funding))}${row('Details',esc(o.fundInfo))}</div>
<div class="panel"><h3>Application requirements</h3><small>${dn} / ${o.reqs.length} completed</small>${o.reqs.map((r,i)=>`<div class="row"><label><input type="checkbox" data-act="rchk" data-id="${o.id}" data-i="${i}" ${r.done?'checked':''}> ${esc(r.t)}</label></div>`).join('')||'<br><small>No requirements listed. Use Edit to add some.</small>'}</div>
<div class="panel"><h3>Notes</h3><textarea data-act="onote" data-id="${o.id}" rows="4" style="width:100%" aria-label="Notes">${esc(o.notes||'')}</textarea></div></div>
<div><div class="panel"><h3>Application</h3>${o.url?`<a class="btn" href="${esc(o.url)}" target="_blank" rel="noopener noreferrer">Open application page</a> `:''}<button class="btn p" data-act="start" data-id="${o.id}">${a?'Application started':'Start Application'}</button></div>
${contactPanel(o)}
<div class="panel"><h3>Research areas</h3><div class="row"><span>Yours</span><span>${chips(S.profile.areas)}</span></div><div class="row"><span>This opportunity</span><span>${chips(o.fields)}</span></div><div class="row"><span>Shared</span><span>${chips(sh,'ok')}</span></div></div>
<div class="panel"><h3>Activity</h3>${o.log.slice(0,8).map(x=>`<div class="row"><span>${esc(x.t)}</span><small>${new Date(x.d).toLocaleDateString()}</small></div>`).join('')}</div></div></div>`};
function oppForm(id){const o=id?opp(id):{},d=document.getElementById('dlg'),inp=(n,l,v,x='')=>`<label>${l}<input name="${n}" value="${esc(v||'')}" ${x}></label>`;
d.innerHTML=`<form><h3 style="font-size:17px;margin-top:0">${id?'Edit opportunity':'Add Opportunity'}</h3><small>Save an opportunity you found so you can track it later.</small>
<h3>Basic information</h3>${inp('title','Opportunity name',o.title,'required placeholder="MSc Microbiology — Antimicrobial Resistance"')}${inp('inst','University / institution',o.inst,'required placeholder="University of Toronto"')}<label>Country${sel('country',['',...COUNTRIES],o.country)}</label>${inp('city','City (optional)',o.city)}<label>Degree level${sel('degree',DEGREES,o.degree)}</label>${inp('fields','Field / research areas (comma separated)',(o.fields||[]).join(', '),'placeholder="Microbiology, Genomics"')}
<h3>Funding</h3><label>Funding type${sel('funding',FUNDING,o.funding)}</label>${inp('fundInfo','Funding information',o.fundInfo,'placeholder="Full tuition + annual stipend"')}
<h3>Deadline</h3>${inp('deadline','Deadline',o.deadline,'type=date')}
<h3>Application</h3>${inp('url','Application URL',o.url,'type=url placeholder="https://"')}<label>Where did you find it?${sel('source',SOURCES,o.source)}</label><label>Requirements (one per line)<textarea name="reqs" rows="3">${esc((o.reqs||[]).map(r=>r.t).join('\n'))}</textarea></label><label>Eligibility notes<textarea name="elig" rows="2">${esc(o.elig||'')}</textarea></label>
<h3>Research / supervisor</h3>${inp('supervisor','Professor / supervisor (optional)',o.supervisor)}<h3>Notes</h3><textarea name="notes" rows="3">${esc(o.notes||'')}</textarea>
<h3>Tracking</h3><label>Status${sel('status',OSTAT,o.status||'Interested')}</label><label>Priority${sel('priority',PRIO,o.priority||'Medium')}</label>
<div class="bar" style="margin-top:14px"><button class="btn p" type="submit">Save Opportunity</button><button class="btn" type="button" data-act="closedlg">Cancel</button></div></form>`;
d.querySelector('form').onsubmit=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target)),old=id?opp(id):null,now=new Date().toISOString();
const rec=normOpp({...(old||{id:'o'+Date.now(),added:now,saved:false}),...f,fields:f.fields.split(',').map(x=>x.trim()).filter(Boolean),reqs:f.reqs.split('\n').map(x=>x.trim()).filter(Boolean).map(t=>({t,done:!!(old&&old.reqs.some(r=>r.t===t&&r.done))})),log:[{d:now,t:old?'Edited':'Opportunity added'},...(old?old.log:[])]});
S.opps=old?S.opps.map(x=>x.id===id?rec:x):[...S.opps,rec];save();d.close();render();toast('Opportunity saved')};d.showModal()}
document.addEventListener('change',e=>{const t=e.target,id=t.dataset.id,o=id&&opp(id);
if(t.dataset.act==='ost'){o.status=t.value;o.log.unshift({d:new Date().toISOString(),t:'Status changed to '+t.value});save();render();toast('Status updated: '+t.value)}
else if(t.dataset.act==='ofil'){ofl[t.dataset.k]=t.value;render()}
else if(t.dataset.act==='rchk'){o.reqs[t.dataset.i].done=t.checked;save();render()}
else if(t.dataset.act==='onote'){o.notes=t.value;o.log.unshift({d:new Date().toISOString(),t:'Notes updated'});save();toast('Notes saved')}});

const CST=['Not contacted','Email sent','Follow-up due','Responded','No response','Interested'];
function contactPanel(o){const ps=S.prof.filter(p=>p.oid===o.id);return `<div class="panel"><div class="row" style="border:0;padding:0"><h3 style="margin:0">Supervisor / contact</h3><button class="btn" data-act="addprof" data-k="${o.id}">Add contact</button></div>${ps.map(p=>`<div class="row"><div><span class="lnk" data-act="profm" data-id="${p.id}">${esc(p.name)}</span><small>${esc(p.inst)}</small><small>Last contact ${p.contacted?fmt(p.contacted):'—'}${p.followUp?' · follow-up '+fmt(p.followUp):''}</small></div><span class="tag">${esc(p.stage)}</span></div>`).join('')||'<small>No contact added.</small>'}</div>`}
document.addEventListener('input',e=>{if(e.target.id==='oq'){oq=e.target.value;render();const i=document.getElementById('oq');i.focus();i.setSelectionRange(oq.length,oq.length)}});
