const dueTag=p=>{if(!p.followUp)return'';const d=days(p.followUp);return d<0?'<span class="tag urgent">Overdue</span>':d===0?'<span class="tag attn">Due today</span>':d===1?'<span class="tag">Tomorrow</span>':''};
views.outreach=()=>`<div class="bar" style="justify-content:space-between"><div><h2>Outreach</h2><p class="sub" style="margin:0">Keep track of professors and supervisors you have contacted.</p></div><button class="btn p" data-act="addprof">+ Add Professor</button></div>
${S.prof.length?'':empty('No professors yet.','<button class="btn p" data-act="addprof">+ Add Professor</button>')}
<div class="kan">${OST.map(s=>`<section data-drop="${s}" data-k="p"><h3>${s.toUpperCase()} · <span data-count="p:${s}">${S.prof.filter(p=>p.stage===s).length}</span></h3>${S.prof.filter(p=>p.stage===s).map(p=>`<div class="card" data-drag="p" data-id="${p.id}"><span class="drag-handle" role="button" aria-label="Drag to move">⋮⋮</span><b class="lnk" data-act="profm" data-id="${p.id}">${esc(p.name)}</b><br><small>${esc(p.inst)}<br>${esc(p.area)}<br>Contacted: ${p.contacted?fmt(p.contacted):'—'}</small> ${dueTag(p)}<select data-act="pmove" data-id="${p.id}" aria-label="Stage" style="width:100%;margin-top:8px">${OST.map(x=>`<option ${x===p.stage?'selected':''}>${x}</option>`).join('')}</select></div>`).join('')}</section>`).join('')}</div>`;
function profModal(id){const p=S.prof.find(x=>x.id===id),o=opp(p.oid),d=document.getElementById('dlg'),r=(l,v)=>v?`<div class="row"><span>${l}</span><span>${v}</span></div>`:'';
d.innerHTML=`<h3 style="font-size:17px;margin-top:0">${esc(p.name)}</h3>${r('University',esc(p.inst))}${r('Research area',esc(p.area))}${r('Email',p.email?`<a href="mailto:${esc(p.email)}">${esc(p.email)}</a>`:'')}${r('Website',p.web?`<a href="${esc(p.web)}" target="_blank" rel="noopener noreferrer">${esc(p.web)}</a>`:'')}${r('Status',esc(p.stage))}${r('Contacted',p.contacted?fmt(p.contacted):'')}${r('Follow-up',p.followUp?fmt(p.followUp):'')}${r('Opportunity',o.title?`<span class="lnk" data-act="openopp" data-id="${o.id}">${esc(o.title)}</span>`:'')}${r('Notes',esc(p.notes))}
<label>Move stage<select data-act="pmove" data-id="${p.id}">${OST.map(s=>`<option ${s===p.stage?'selected':''}>${s}</option>`).join('')}</select></label><div class="bar" style="margin-top:12px"><button class="btn p" data-act="pedit" data-id="${p.id}">Edit Contact</button><button class="btn" data-act="pdone" data-id="${p.id}">Mark Follow-up Complete</button><button class="btn" data-act="closedlg">Close</button></div>`;d.showModal()}
function profForm(id,oid){const p=id?S.prof.find(x=>x.id===id):{stage:'Ready to contact',contacted:D(0),oid:oid||''},d=document.getElementById('dlg'),i=(n,l,x='')=>`<label>${l}<input name="${n}" value="${esc(p[n]||'')}" ${x}></label>`;
d.innerHTML=`<form><h3 style="font-size:17px;margin-top:0">${id?'Edit contact':'Add Professor'}</h3>${i('name','Professor name','required')}${i('inst','University','required')}${i('area','Research area')}${i('email','Email','type=email')}${i('web','Website','type=url')}<label>Status${sel('stage',OST,p.stage)}</label>${i('contacted','Contacted date','type=date')}${i('followUp','Follow-up date','type=date')}<label>Linked opportunity<select name="oid"><option value="">None</option>${S.opps.map(o=>`<option value="${o.id}" ${o.id===p.oid?'selected':''}>${esc(o.title)}</option>`).join('')}</select></label><label>Notes<textarea name="note" rows="2">${esc(p.note||'')}</textarea></label><div class="bar" style="margin-top:14px"><button class="btn p" type="submit">Save</button><button class="btn" type="button" data-act="closedlg">Cancel</button></div></form>`;
d.querySelector('form').onsubmit=e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));f.notes=f.note;if(id)Object.assign(p,f);else S.prof.push({id:'p'+Date.now(),pubs:[],areas:[],gaps:[],...f});save();d.close();render();toast('Contact saved')};d.showModal()}
Object.assign(ACTIONS,{profm:id=>profModal(id),addprof:(id,t)=>profForm(null,t&&t.dataset.k),pedit:id=>profForm(id),
pdone(id){const p=S.prof.find(x=>x.id===id);p.stage='Email sent';p.contacted=D(0);p.followUp='';save();document.getElementById('dlg').close();render();toast('Follow-up marked complete')}});
document.addEventListener('change',e=>{const t=e.target;if(t.dataset.act!=='pmove')return;moveProfessor(t.dataset.id,t.value)});
function moveProfessor(id,stage){const p=S.prof.find(x=>x.id===id);if(!p||p.stage===stage)return;p.stage=stage;if(stage==='Email sent'&&!p.contacted)p.contacted=D(0);save();render();toast('Professor moved to '+stage)}
