// Demo data only. Institutions, people and publications are fictional placeholders, not real opportunities.
const seed=()=>{const H=h=>new Date(Date.now()-h*36e5).toISOString();
const O=[['MSc Microbiology (AMR)','University of Toronto','Canada','Masters','Fully Funded','microbiology, antimicrobial resistance',48,'Official university website',1,2],
['PhD Studentship in AMR','University of Freiburg','Germany','PhD','Fully Funded','antimicrobial resistance, genomics',64,'Official university website',1,26],
['MSc Infectious Disease','University of Edinburgh','United Kingdom','Masters','Partially Funded','infectious disease',80,'FindAPhD listing',0,50],
['PhD One Health','University of Guelph','Canada','PhD','Fully Funded','one health, food safety',22,'Official university website',1,5],
['Bioinformatics PhD','Heidelberg University','Germany','PhD','Stipend','bioinformatics, genomics',6,'DAAD portal',1,90],
['Public Health MSc','Wageningen University','Netherlands','Masters','Partially Funded','public health',58,'LinkedIn post',0,30],
['Bacterial Genomics PhD','Johns Hopkins University','United States','PhD','Fully Funded','genomics, infectious disease',35,'Official university website',1,12],
['Host-Pathogen RA','University of Melbourne','Australia','PhD','Research Assistantship','host-pathogen interaction',-3,'LinkedIn post',0,200]]
.map((o,i)=>({id:'o'+i,title:o[0],inst:o[1],country:o[2],degree:o[3],funding:o[4],field:o[5],deadline:D(o[6]),source:o[7],added:H(o[9]),saved:i===0||i===4,status:['Preparing','Applied','Researching','Preparing','Preparing','Applied','Interested','Archived'][i]}));
const pub=(t,y,j,g)=>({title:t,year:y,journal:j,tags:g});
const P=[['Dr. A. Rahman','University of Toronto','Environmental AMR','Email sent',-11,'o0',['Antimicrobial resistance','Environmental microbiology','Bacterial genomics','Host-pathogen interaction'],['Metabolomics','Structural biology'],[pub('Wastewater surveillance of antimicrobial resistance',2025,'Demo J. Antimicrobial Chemotherapy',['AMR','Wastewater','Genomics']),pub('Long-read sequencing of resistance plasmids',2024,'Demo Microbial Genomics',['Genomics','AMR'])]],
['Prof. L. Weber','University of Freiburg','AMR genomics','Response received',-5,'o1',['Antimicrobial resistance','Bacterial genomics','Bioinformatics','Infectious disease'],['Environmental sampling'],[pub('Genomic epidemiology of resistant Enterobacterales',2025,'Demo Genome Research',['AMR','Genomics','Surveillance']),pub('Pipelines for pathogen genome assembly',2023,'Demo Bioinformatics Methods',['Bioinformatics'])]],
['Dr. S. Okafor','University of Edinburgh','Infectious disease','Ready to contact',0,'o2',['Infectious disease','Host-pathogen interaction','Antimicrobial resistance'],['Genomics','Bioinformatics'],[pub('Host response to bacterial bloodstream infection',2024,'Demo Infection & Immunity',['Host-pathogen','Infectious disease']),pub('Antibiotic tolerance in clinical isolates',2025,'Demo Clinical Microbiology',['AMR','Clinical'])]],
['Prof. M. Hughes','University of Guelph','One Health','Email sent',-3,'o3',['One health','Food safety','Antimicrobial resistance','Environmental microbiology'],['Molecular modelling'],[pub('Resistance in food-chain bacteria across farms',2025,'Demo One Health Journal',['One Health','AMR','Food safety']),pub('Farm wastewater as a surveillance signal',2024,'Demo Applied Microbiology',['Wastewater','AMR'])]],
['Dr. J. Tan','Heidelberg University','Computational genomics','Follow-up due',-9,'o4',['Bioinformatics','Genomics','Bacterial genomics','CRISPR-Cas systems'],['Wet-lab microbiology','Metabolomics'],[pub('Scalable comparison of bacterial genomes',2025,'Demo Nucleic Acids Methods',['Genomics','Bioinformatics']),pub('CRISPR-Cas diversity in environmental isolates',2024,'Demo Molecular Microbiology',['CRISPR','Genomics'])]]]
.map((p,i)=>({id:'p'+i,name:p[0],inst:p[1],area:p[2],stage:p[3],contacted:D(p[4]),oid:p[5],areas:p[6],gaps:p[7],pubs:p[8],note:'Demo contact'}));
const A=[['o0','Preparing','High',[1,1,1,1,0,0]],['o4','Preparing','High',[1,1,0,1,0,0]],['o3','Preparing','Medium',[1,1,1,1,1,0]],['o1','Submitted','High',[1,1,1,1,1,1]],['o2','Researching','Medium',[1,0,0,0,0,0]],['o6','Researching','Low',[1,0,0,0,0,0]],['o5','Interview','Medium',[1,1,1,1,1,1]],['o7','Rejected','Low',[1,1,1,1,1,1]]]
.map((a,i)=>({id:'a'+i,oid:a[0],status:a[1],priority:a[2],done:a[3],updated:D(-i)}));
return {profile:{areas:['antimicrobial resistance','microbiology','infectious disease','bioinformatics','genomics','one health'],methods:['whole genome sequencing','antimicrobial susceptibility testing','molecular microbiology'],keywords:['AMR','CRISPR','bacterial genomics','wastewater','pathogen surveillance'],countries:['Canada','Germany','United Kingdom','United States'],experience:'environmental AMR surveillance and bacterial genomics',degreeGoal:'Both'},
opps:O,apps:A,prof:P,docsList:['CV','Statement of purpose','Research proposal','Transcript','Recommendation letter','English test'],userName:'',demo:true,onboarded:false,doneActions:[],doneDate:''}};
