const RAW=[['ambition','Stay hungry. Stay foolish.','Steve Jobs'],['focus','The only way to do great work is to love what you do.','Steve Jobs'],['education','Education is the most powerful weapon which you can use to change the world.','Nelson Mandela'],['failure',"I can accept failure, everyone fails at something. But I can't accept not trying.",'Michael Jordan'],['ambition','The biggest adventure you can take is to live the life of your dreams.','Oprah Winfrey'],['discipline','Discipline is the bridge between goals and accomplishment.','Jim Rohn'],['resilience','Fall forward.','Denzel Washington'],['beginnings','A journey of a thousand miles begins with a single step.','Lao Tzu'],['progress','If there is no struggle, there is no progress.','Frederick Douglass'],['education','One child, one teacher, one book, one pen can change the world.','Malala Yousafzai'],['achievement','Nothing great was ever achieved without enthusiasm.','Ralph Waldo Emerson'],['failure','Ever tried. Ever failed. No matter. Try again. Fail again. Fail better.','Samuel Beckett'],
['discipline','Do the task you have been avoiding first. The day gets lighter after that.'],['discipline','Motivation starts the work. Discipline finishes it.'],['discipline','Make the plan small enough that you cannot argue with it.'],
['perseverance','A rejection is information, not a verdict. Adjust and send the next one.'],['perseverance','Keep the application moving, even when the pace is slow.'],['perseverance','You do not need a perfect day. You need a day that moves one thing forward.'],
['ambition','Aim at the programme you want, then build the steps that lead to it.'],['ambition','Large goals are completed one small, finished task at a time.'],
['consistency','Ten focused minutes every day beat one heroic weekend.'],['consistency','Show up to your list today, even briefly.'],['consistency','Steady effort quietly outruns last-minute panic.'],
['courage','Send the email. The worst outcome is silence, and silence can be followed up.'],['courage','Apply to the one that feels slightly out of reach.'],
['resilience','Setbacks are part of the path. Note what you learned and continue.'],['resilience','One closed door leaves the rest of your list untouched.'],
['patience','Good decisions take time. Let the process run and do your part.'],['patience','Waiting is not idleness when you have prepared well.'],
['education','Every document you write is practice for the work you are about to do.'],['education','You are investing in what you can do, not only in a certificate.'],
['focus','Close every tab except the one that serves this application.'],['focus','Choose one priority. Finish it. Then choose again.'],['focus','Clarity comes from deciding what to do next, not from thinking longer.'],
['achievement','Submitting an application is an achievement. Mark it, then move on.'],['achievement','Look at what you finished this week, not only at what remains.'],
['beginnings','Open the document and write one sentence. That is the start.'],['beginnings','A rough first draft is worth more than a perfect idea.'],
['failure','A weak draft is not failure. It is the first version.'],['failure','Learn from the result, update the plan, and try again.'],
['progress','Look back at where your list started. You have already moved.'],['progress','Progress is measured by tasks completed, not by how you feel about them.'],
['rest','Rest is part of the work. Close the laptop without guilt.'],['rest','Sleep helps tomorrow\'s writing more than another late hour does.'],
['reflection','Before you finish, write down tomorrow\'s first task.'],['reflection','Notice one thing you handled well today.']];
const LIB=RAW.map((r,i)=>({id:i+1,cat:r[0],text:r[1],author:r[2]||'FundTrack',sourceType:r[2]?'quote':'original'}));
const PERIOD_CATS={morning:['ambition','focus','discipline','beginnings'],afternoon:['consistency','perseverance','progress','courage'],evening:['reflection','achievement','progress','education'],night:['rest','resilience','patience','failure']};
S.motiv={on:true,auto:false,vol:1,voice:'',rotate:true,interval:45,...S.motiv};
let queue=[],cur=null,paused=false,rot;
const byline=m=>m.author==='FundTrack'?'FundTrack Original':m.author;
const pool=()=>{const c=PERIOD_CATS[periodOf(new Date().getHours())],p=LIB.filter(m=>c.includes(m.cat));return p.length>3?p:LIB};
function getMotivationByTime(){if(!queue.length){queue=pool().map(m=>m.id).sort(()=>Math.random()-.5);if(cur&&queue.length>1&&queue[queue.length-1]===cur.id)queue.unshift(queue.pop())}
const id=queue.pop();cur=LIB.find(m=>m.id===id);return cur}
function nextMoment(){const m=getMotivationByTime(),el=document.getElementById('mom');if(el&&el.animate){el.animate([{opacity:1},{opacity:0}],{duration:200});setTimeout(()=>{document.getElementById('mom-text').textContent='“'+m.text+'”';document.getElementById('mom-by').textContent='— '+byline(m);el.animate([{opacity:0},{opacity:1}],{duration:300})},200)}return m}
function schedule(){clearTimeout(rot);if(!S.motiv.rotate||paused)return;rot=setTimeout(()=>{if(document.getElementById('mom-text'))nextMoment();schedule()},S.motiv.interval*1000);rot.unref&&rot.unref()}
const speechOk=()=>typeof speechSynthesis!=='undefined'&&typeof SpeechSynthesisUtterance!=='undefined';
function stopMotivation(){if(speechOk())speechSynthesis.cancel()}
function playMotivation(text){if(!speechOk())return toast('Speech is not supported in this browser');stopMotivation();const u=new SpeechSynthesisUtterance(text||(cur?cur.text:getMotivationByTime().text));u.volume=S.motiv.vol;const v=speechSynthesis.getVoices().find(x=>x.name===S.motiv.voice);if(v)u.voice=v;speechSynthesis.speak(u)}
const toggleMotivation=()=>speechOk()&&speechSynthesis.speaking?stopMotivation():playMotivation();
function momentHtml(){const m=cur||getMotivationByTime();return `<div class="panel" id="mom"><small class="eyebrow">Moment of the day</small><p id="mom-text" style="font-size:20px;font-weight:300;margin:8px 0 4px">“${esc(m.text)}”</p><small id="mom-by">— ${esc(byline(m))}</small><div class="bar" style="margin:10px 0 0"><button class="btn" data-act="mnext">↻ Next</button>${S.motiv.rotate?`<button class="btn" data-act="mpause">${paused?'Resume':'Pause'}</button>`:''}${S.motiv.on?'<button class="btn" data-act="mlisten">🔊 Listen</button><button class="btn" data-act="mstop">Stop</button>':''}</div></div>`}
const baseSettings=views.settings;
views.settings=()=>{const m=S.motiv,vs=speechOk()?speechSynthesis.getVoices():[],ck=(k,l)=>`<label><input type="checkbox" data-act="mset" data-k="${k}" ${m[k]?'checked':''}> ${l}</label>`;
return baseSettings()+`<div class="panel"><h3>Motivation</h3>${ck('rotate','Automatic quote rotation')}${ck('on','Voice')}${ck('auto','Auto-play voice (off by default)')}<label>Rotation interval<select data-act="mset" data-k="interval">${[30,45,60,90].map(n=>`<option value="${n}" ${n===m.interval?'selected':''}>${n} sec</option>`).join('')}</select></label><label>Voice<select data-act="mset" data-k="voice"><option value="">System default</option>${vs.map(v=>`<option ${v.name===m.voice?'selected':''}>${esc(v.name)}</option>`).join('')}</select></label><div class="bar" style="margin-top:10px"><button class="btn" data-act="mlisten">Test Voice</button><button class="btn" data-act="mstop">Stop</button></div></div>`};
Object.assign(ACTIONS,{mnext(){nextMoment();schedule()},mpause(){paused=!paused;schedule();render()},mlisten:()=>playMotivation(),mstop:stopMotivation});
document.addEventListener('change',e=>{const t=e.target;if(t.dataset.act!=='mset')return;S.motiv[t.dataset.k]=t.type==='checkbox'?t.checked:t.dataset.k==='interval'?+t.value:t.value;save();schedule()});
let armed=false;document.addEventListener('click',()=>{if(armed||view!=='overview'||!S.motiv.on||!S.motiv.auto)return;armed=true;playMotivation()});schedule();
